### ISSUE TITLE
Новый skin.py.

### ISSUE THREAD

**Issue by 68foxboris** [Sirius0103/enigma2-skins#2]
Добрый день.На OpenPli будут изменения skin.py и скин не стартует из за этой ошибки

`
[Skin] Error: Unable to parse skin data in '/usr/share/enigma2/CyberFHD/skin.xml' - '[Skin] {CyberFHD/skin.xml}: Bad parameter: 'invalid literal for int() with base 10: 'cyan''!  Please contact the skin's author!'!
[Skin] Error: Adding current GUI skin 'CyberFHD/skin.xml' has failed!
`
<parameter name="VirtualKeyBoardShiftColors" value="white,white,cyan,yellow" />
Нет этого цвета в colors.

И ещё некоторые ошибки
`
[Skin] Processing screen 'UnhandledKey', position=(810, 200), size=(300 x 300) for module 'UnhandledKey'.
warning, skin is missing element UnhandledKeyPixmap in <class 'Screens.UnhandledKey.UnhandledKey'>
[Skin] Processing screen 'Dish', position=(810, 200), size=(300 x 300) for module 'Dish'.
warning, skin is missing element From in <class 'Screens.Dish.Dish'>
warning, skin is missing element Goto in <class 'Screens.Dish.Dish'>
[Skin] No skin to read or screen to display.
[Skin] Processing screen '<embedded-in-BufferIndicator>', position=(?, ?), size=(? x ?) for module 'BufferIndicator'.
warning, skin is missing element status in <class 'Screens.InfoBarGenerics.BufferIndicator'>
[Skin] Processing screen 'TimeshiftState', position=(0, 0), size=(1920 x 170) for module 'TimeshiftState'.
[Skin] No skin to read or screen to display.
[Skin] Processing screen '<embedded-in-TimeshiftLive>', position=(?, ?), size=(? x ?) for module 'TimeshiftLive'.
[Skin] Processing screen 'SubtitleDisplay', position=(0, 0), size=(1920 x 1080) for module 'SubtitleDisplay'.
warning, skin is missing element message in <class 'Screens.SubtitleDisplay.SubtitleDisplay'>
RemovePopup, id = ZapError
[Skin] Processing screen 'InfoBar', position=(0, 0), size=(1920 x 1080) for module 'InfoBar'.
[Skin] Processing screen 'InfoBarSummary', position=(0, 0), size=(1 x 1) for module 'InfoBarSummary'.
[Skin] Processing screen 'Volume', position=(0, 0), size=(1920 x 170) for module 'Volume'.
warning, skin is missing element VolumeText in <class 'Screens.Volume.Volume'>
[Skin] Processing screen 'TimerEditList', position=(0, 0), size=(1920 x 1080) for module 'TimerEditList'.
warning, skin is missing element description in <class 'Screens.TimerEdit.TimerEditList'>
[Skin] Processing screen 'CronTimers', position=(0, 0), size=(1920 x 1080) for module 'CronTimers'.
warning, skin is missing element key in <class 'Screens.CronTimer.CronTimers'>
[Skin] Processing screen 'DreamExplorerII', position=(0, 0), size=(1920 x 1080) for module 'DreamExplorerII'.
warning, skin is missing element TEMPfl in <class 'Plugins.Extensions.DreamExplorer.plugin.DreamExplorerII'>

`

**Comment by Sirius0103** [comment]
**68foxboris** спасибо

> Нет этого цвета в colors.
исправил
