### ISSUE TITLE
Графический переключатель.

### ISSUE THREAD

**Issue by 68foxboris** [Sirius0103/enigma2-skins#3]
Добрый день.Я добавил эти строки и иконки
`
    <switchpixmap>
    <pixmap name="menu_on" filename="icons/menu_on.png" />
    <pixmap name="menu_off" filename="icons/menu_off.png" />
    </switchpixmap>
`
и появились графические переключатели.
![1_0_1_7923_1F_FD_1680000_0_0_0_20200420104100](https://user-images.githubusercontent.com/17230642/79726660-d32fa400-82f3-11ea-9ac7-c73b797df0d2.jpg)
И почему-то в меню-плагины-как бы наложение строк есть,хотя может это только у меня.
![1_0_1_7923_1F_FD_1680000_0_0_0_20200420104127](https://user-images.githubusercontent.com/17230642/79726763-fd816180-82f3-11ea-9146-ff866a962ec4.jpg)

**Comment by Sirius0103** [comment]
добавил...
